language: node_js
node_js:
- '10'
deploy:
  provider: heroku
  api_key:
    secure: BJ1HurB2VH9OQBcxeqqw7oc0zdwRrVZ8Dlu1hIAh9w7D699dDCxOCeYtrJ4uUyieHatJ4Y2bWOKnPU2VCJyZgmL2YjGUhUBWDFfKzxHFFgYfHdW8I1EQ/gLZWqIXbmGr2KKIL9YOFtlRqMFE1Dkb5tpmNIXuNrMDJmBrQ4NV2DKoEI2U68t2HNt1VeK0i8MfI9LjpRug/BOIRqWiA8CmPkgZJgbkUhAyAKuTSHecLFHBzu4ONq1rFeL5waZstWaeDeHrpi4iOtVaClA/1ti1B1O/nvxh1xaGRk+MABQHuYmmZlcX9IeyowZiogcwdqz7ZzU0j2NwvJQd3lsxQVczSGlL2oNaO3uH5Q2bA9zQYSagW8qcSftwBHVWkZYx3xdPSvWc2BsEna+Rr+/w0Io7DQ1ys2PYh9Zh61lovrZtK97iXnKkw8Q3QtXQ9rQQS+W2rrIAjQvzZzWp1YAVGzYIn0LSvty5zzwD9a9NDvT9N7g9PoavXbO+Es+AMYx6RwMPgsvzSh4BiyBo4tWnSW6t4iItTQsEWtgnoUiNly2VG8DSQ7wOnAaQxs4NM0Z8g4cA2VcbMegGoBtaWgRMPVovFyuFrJba7sKUTnfuN3dq7DcSwnQNq7sXBlMhjkgML+jtrEL4/ttq7RN53Tb4pnIhbnmcxkgKlClkN0fyDnPXA7M=
  app: polar-ocean-65786
  on:
    repo: lightsage88/crosspadAPI
